Build with mariadb_config flag

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,14 +1,20 @@
 #!/bin/sh
 
-detect () {
-  gcc -o /dev/null detect/detect.c $@ > /dev/null 2>&1
-  return $?
-}
+config_binary=""
+
+if command -v mariadb_config ; then
+  config_binary=`command -v mariadb_config`
+fi
+
+if [ -z "$config_binary" ]; then
+  echo "Could not find mariadb_config" 1>&2
+  exit 1
+fi
 
 include_base=""
 mariadb_connector="false"
 
-if detect -lmariadb; then
+if true; then
   include_base="mariadb"
   mariadb_connector="true"
 elif detect -lmysqlclient -DMARIADB_CLIENT; then
@@ -20,13 +26,20 @@ if [ -z "$include_base" ]; then
   exit 1
 fi
 
+mariadb_config_cflags=`$config_binary --cflags`
+mariadb_config_libs=`$config_binary --libs`
 
 echo "mariadb_connector: ................................... $mariadb_connector"
 echo "mariadb_include_base: ................................ $include_base"
+echo "mariadb_config_cflags: ............................... $mariadb_config_cflags"
+echo "mariadb_config_libs: ................................. $mariadb_config_libs"
+
 
 cat << EOF > setup.data
 mariadb_include_base="$include_base"
 mariadb_connector="$mariadb_connector"
+mariadb_config_cflags="$mariadb_config_cflags"
+mariadb_config_libs="$mariadb_config_libs"
 EOF
 
 # OASIS_START
